name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Add Dicord token
        run: |
          sed -i 's/Your Discord Token/${{ secrets.DISCORD_TOKEN }}/g' .env
          sed -i 's/Your KSoft API Token/${{ secrets.KSOFT_TOKEN }}/g' .env
      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: ./
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: /.git/
      - name: Start Docker container
        uses: garygrossgarten/github-action-ssh@v0.6.3
        with:
          command: |
            cd ${{ secrets.REMOTE_TARGET }}
            docker-compose down
            docker-compose build
            docker-compose up -d
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
